2025-04-10 11:56:39,858 INFO: Starting advanced check task for URL ID 3 [in /home/patrik/Documents/work/WEB-test/app/tasks.py:58]
2025-04-10 11:56:41,773 INFO: Advanced check task for URL ID 3: Session committed successfully. [in /home/patrik/Documents/work/WEB-test/app/tasks.py:78]
2025-04-10 11:56:48,026 INFO: Starting full scan for https://awesome.com (ID: 3) by user patrik [in /home/patrik/Documents/work/WEB-test/app/routes.py:451]
2025-04-10 11:56:49,754 ERROR: Traceroute command 'traceroute' not found for hostname awesome.com. [in /home/patrik/Documents/work/WEB-test/app/checks.py:183]
2025-04-10 11:56:49,777 INFO: Full scan completed successfully for https://awesome.com (ID: 3) and results saved. [in /home/patrik/Documents/work/WEB-test/app/routes.py:479]
2025-04-10 11:59:39,103 INFO: Application startup [in /home/patrik/Documents/work/WEB-test/app/__init__.py:74]
2025-04-10 11:59:39,109 INFO: Scheduler started. [in /home/patrik/Documents/work/WEB-test/app/__init__.py:151]
2025-04-10 11:59:39,109 INFO: Attempting to schedule initial jobs... [in /home/patrik/Documents/work/WEB-test/app/__init__.py:78]
2025-04-10 11:59:39,129 INFO: Found 3 URLs in the database for initial scheduling. [in /home/patrik/Documents/work/WEB-test/app/__init__.py:83]
2025-04-10 11:59:39,172 INFO: Scheduled initial immediate advanced check job 'advanced_check_url_3_initial' for URL ID 3 [in /home/patrik/Documents/work/WEB-test/app/__init__.py:139]
2025-04-10 11:59:39,174 INFO: Starting advanced check task for URL ID 3 [in /home/patrik/Documents/work/WEB-test/app/tasks.py:58]
2025-04-10 11:59:40,550 INFO: Advanced check task for URL ID 3: Session committed successfully. [in /home/patrik/Documents/work/WEB-test/app/tasks.py:78]
2025-04-10 11:59:52,328 ERROR: Exception on /url_details/1 [GET] [in /var/data/python/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/var/data/python/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/python/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/python/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/python/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/python/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/patrik/Documents/work/WEB-test/app/routes.py", line 264, in view_url_details
    return render_template(
           ^^^^^^^^^^^^^^^^
  File "/var/data/python/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/python/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/python/lib/python3.12/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/var/data/python/lib/python3.12/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/patrik/Documents/work/WEB-test/templates/url_details.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/patrik/Documents/work/WEB-test/templates/base.html", line 53, in top-level template code
    {% block app_content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/patrik/Documents/work/WEB-test/templates/url_details.html", line 133, in block 'app_content'
    {% for type, records in scan_results.dns.items() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/python/lib/python3.12/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'None' has no attribute 'items'
2025-04-10 11:59:58,560 WARNING: Standard check job check_url_1 not found for URL ID 1, skipping removal. [in /home/patrik/Documents/work/WEB-test/app/routes.py:161]
2025-04-10 11:59:58,564 WARNING: Recurring advanced check job advanced_check_url_1 not found for URL ID 1, skipping removal. [in /home/patrik/Documents/work/WEB-test/app/routes.py:170]
2025-04-10 12:00:01,100 INFO: Removed standard check job check_url_2 for URL ID 2 [in /home/patrik/Documents/work/WEB-test/app/routes.py:159]
2025-04-10 12:00:01,112 INFO: Removed advanced check job advanced_check_url_2 for URL ID 2 [in /home/patrik/Documents/work/WEB-test/app/routes.py:168]
2025-04-10 12:00:05,639 INFO: Removed standard check job check_url_3 for URL ID 3 [in /home/patrik/Documents/work/WEB-test/app/routes.py:159]
2025-04-10 12:00:05,651 INFO: Removed advanced check job advanced_check_url_3 for URL ID 3 [in /home/patrik/Documents/work/WEB-test/app/routes.py:168]
2025-04-10 12:00:08,714 INFO: Scheduled standard check for new URL https://clipron.com (ID: 1) [in /home/patrik/Documents/work/WEB-test/app/routes.py:108]
2025-04-10 12:00:08,726 INFO: Scheduled recurring advanced check for new URL https://clipron.com (ID: 1) [in /home/patrik/Documents/work/WEB-test/app/routes.py:120]
2025-04-10 12:00:08,747 INFO: Scheduled initial immediate advanced check for new URL https://clipron.com (ID: 1) [in /home/patrik/Documents/work/WEB-test/app/routes.py:130]
2025-04-10 12:00:08,752 INFO: Starting advanced check task for URL ID 1 [in /home/patrik/Documents/work/WEB-test/app/tasks.py:58]
2025-04-10 12:00:13,406 INFO: Scheduled standard check for new URL https://gmail.com (ID: 2) [in /home/patrik/Documents/work/WEB-test/app/routes.py:108]
2025-04-10 12:00:13,419 INFO: Scheduled recurring advanced check for new URL https://gmail.com (ID: 2) [in /home/patrik/Documents/work/WEB-test/app/routes.py:120]
2025-04-10 12:00:13,430 INFO: Scheduled initial immediate advanced check for new URL https://gmail.com (ID: 2) [in /home/patrik/Documents/work/WEB-test/app/routes.py:130]
2025-04-10 12:00:13,432 INFO: Starting advanced check task for URL ID 2 [in /home/patrik/Documents/work/WEB-test/app/tasks.py:58]
2025-04-10 12:00:14,450 INFO: Advanced check task for URL ID 2: Session committed successfully. [in /home/patrik/Documents/work/WEB-test/app/tasks.py:78]
2025-04-10 12:00:17,161 INFO: Scheduled standard check for new URL https://awesome.com (ID: 3) [in /home/patrik/Documents/work/WEB-test/app/routes.py:108]
2025-04-10 12:00:17,173 INFO: Scheduled recurring advanced check for new URL https://awesome.com (ID: 3) [in /home/patrik/Documents/work/WEB-test/app/routes.py:120]
2025-04-10 12:00:17,186 INFO: Scheduled initial immediate advanced check for new URL https://awesome.com (ID: 3) [in /home/patrik/Documents/work/WEB-test/app/routes.py:130]
2025-04-10 12:00:17,189 INFO: Starting advanced check task for URL ID 3 [in /home/patrik/Documents/work/WEB-test/app/tasks.py:58]
2025-04-10 12:00:18,603 INFO: Advanced check task for URL ID 3: Session committed successfully. [in /home/patrik/Documents/work/WEB-test/app/tasks.py:78]
2025-04-10 12:00:19,469 INFO: Advanced check task for URL ID 1: Session committed successfully. [in /home/patrik/Documents/work/WEB-test/app/tasks.py:78]
2025-04-10 12:00:21,565 INFO: Starting full scan for https://clipron.com (ID: 1) by user patrik [in /home/patrik/Documents/work/WEB-test/app/routes.py:460]
2025-04-10 12:00:22,993 ERROR: Traceroute command 'traceroute' not found for hostname clipron.com. [in /home/patrik/Documents/work/WEB-test/app/checks.py:183]
2025-04-10 12:00:23,011 INFO: Full scan completed successfully for https://clipron.com (ID: 1) and results saved. [in /home/patrik/Documents/work/WEB-test/app/routes.py:488]
2025-04-10 12:30:21,615 INFO: Application startup [in /home/patrik/Documents/work/WEB-test/app/__init__.py:74]
2025-04-10 12:30:21,619 INFO: Scheduler started. [in /home/patrik/Documents/work/WEB-test/app/__init__.py:151]
2025-04-10 12:30:21,620 INFO: Attempting to schedule initial jobs... [in /home/patrik/Documents/work/WEB-test/app/__init__.py:78]
2025-04-10 12:30:21,636 INFO: Found 3 URLs in the database for initial scheduling. [in /home/patrik/Documents/work/WEB-test/app/__init__.py:83]
2025-04-10 12:30:21,736 INFO: Scheduled initial immediate advanced check job 'advanced_check_url_3_initial' for URL ID 3 [in /home/patrik/Documents/work/WEB-test/app/__init__.py:139]
2025-04-10 12:30:21,742 INFO: Starting advanced check task for URL ID 3 [in /home/patrik/Documents/work/WEB-test/app/tasks.py:58]
2025-04-10 12:30:23,465 INFO: Advanced check task for URL ID 3: Session committed successfully. [in /home/patrik/Documents/work/WEB-test/app/tasks.py:78]
2025-04-10 12:30:47,682 INFO: Removed standard check job check_url_1 for URL ID 1 [in /home/patrik/Documents/work/WEB-test/app/routes.py:159]
2025-04-10 12:30:47,693 INFO: Removed advanced check job advanced_check_url_1 for URL ID 1 [in /home/patrik/Documents/work/WEB-test/app/routes.py:168]
2025-04-10 12:30:51,550 INFO: Scheduled standard check for new URL https://clipron.com (ID: 4) [in /home/patrik/Documents/work/WEB-test/app/routes.py:108]
2025-04-10 12:30:51,564 INFO: Scheduled recurring advanced check for new URL https://clipron.com (ID: 4) [in /home/patrik/Documents/work/WEB-test/app/routes.py:120]
2025-04-10 12:30:51,576 INFO: Scheduled initial immediate advanced check for new URL https://clipron.com (ID: 4) [in /home/patrik/Documents/work/WEB-test/app/routes.py:130]
2025-04-10 12:30:51,580 INFO: Starting advanced check task for URL ID 4 [in /home/patrik/Documents/work/WEB-test/app/tasks.py:58]
